import { Router } from 'express';
import authRoutes from './auth';
import settingsRoutes from './settings';
import seoRoutes from './seo';
import heroSlideRoutes from './heroSlides';
import initiativeRoutes from './initiatives';
import campaignRoutes from './campaigns';
import campaignCategoryRoutes from './campaignCategories';
import updateRoutes from './updates';
import teamRoutes from './team';
import galleryRoutes from './gallery';
import testimonialRoutes from './testimonials';
import impactRoutes from './impact';
import partnerRoutes from './partners';
import policyRoutes from './policies';
import donationRoutes from './donations';
import volunteerRoutes from './volunteers';
import contactRoutes from './contact';
import partnerApplicationRoutes from './partnerApplications';
import internshipRoutes from './internships';
import faqRoutes from './faqs';
import blogRoutes from './blog';
import campLocationRoutes from './campLocations';
import mediaRoutes from './media';
import cvRequestRoutes from './cvRequests';
import replyRoutes from './replies';
import siteConfigRoutes from './siteConfig';
import siteUpdateRoutes from './siteUpdates';
import footerLinkRoutes from './footerLinks';
import quoteRoutes from './quotes';
import presenceLocationRoutes from './presenceLocations';
import coreValueRoutes from './coreValues';
import formFieldRoutes from './formFields';

const router = Router();

// API v1 routes
router.use('/api/auth', authRoutes);
router.use('/api/settings', settingsRoutes);
router.use('/api/seo', seoRoutes);
router.use('/api/hero-slides', heroSlideRoutes);
router.use('/api/initiatives', initiativeRoutes);
router.use('/api/campaigns', campaignRoutes);
router.use('/api/campaign-categories', campaignCategoryRoutes);
router.use('/api/updates', updateRoutes);
router.use('/api/team', teamRoutes);
router.use('/api/gallery', galleryRoutes);
router.use('/api/testimonials', testimonialRoutes);
router.use('/api/impact-counters', impactRoutes);
router.use('/api/partners', partnerRoutes);
router.use('/api/policies', policyRoutes);
router.use('/api/donations', donationRoutes);
router.use('/api/volunteers', volunteerRoutes);
router.use('/api/contact', contactRoutes);
router.use('/api/partner-applications', partnerApplicationRoutes);
router.use('/api/internships', internshipRoutes);
router.use('/api/faqs', faqRoutes);
router.use('/api/blogs', blogRoutes);
router.use('/api/camp-locations', campLocationRoutes);
router.use('/api/media', mediaRoutes);
router.use('/api/cv-requests', cvRequestRoutes);
router.use('/api/replies', replyRoutes);
router.use('/api/site-config', siteConfigRoutes);
router.use('/api/site-updates', siteUpdateRoutes);
router.use('/api/footer-links', footerLinkRoutes);
router.use('/api/quotes', quoteRoutes);
router.use('/api/presence-locations', presenceLocationRoutes);
router.use('/api/core-values', coreValueRoutes);
router.use('/api/form-fields', formFieldRoutes);

export default router;
